### ISSUE TITLE
Ropsten Will not sync implement fix 

### ISSUE THREAD

**Issue by ZaineJJ** [dappnode/DAppNodePackage-ropsten#44]
Version: 0.3.15 (v1.10.18 upstream)

Stuck on block and regardless restart it just won't sync 
 Local chain is post-merge, waiting for beacon client sync switch-over... 

Found the fix 
https://notes.ethereum.org/@timbeiko/ropsten-ttd-override
added --override.terminaltotaldifficulty 100000000000000000000000 on EXTRA_OPTIONS 

It finally syncs

**Comment by alexpeterson91** [comment]
Don't have much time left. Just a month or so till Ropsten is shutdown permanently.

**Comment by ZaineJJ** [comment]
Ah alright thank you for updating.
